### ISSUE TITLE
Applying ipm to a 2d detection that extends beyond the bottom edge of the image

### ISSUE THREAD

**Issue by ijnek** [ros-sports/soccer_ipm#3]
There is a problem with the ipm method. If the footpoint of a given object is not in the image, and you observe the object e.g. as a bounding box in image space, you might falsely assume that the lowest part of the bounding box is the footpoint. A simple but effective way of mitigating this is to assume that all bounding boxes that end at the bottom of the image might continue to a lower footpoint. They are therefore not projectable and dropped. Otherwise, some weird "alias" projections might occur. Because object detectors like YOLO are not 100% accurate, boxes of objects that continue might end in the lower part of the image instead of exactly the lowest pixel. This method is used to threshold this and sort out objects that would be projected to a wrong position (really messes with filters and stuff) otherwise.

_Originally posted by @Flova in https://github.com/ros-sports/soccer_ipm/pull/1#discussion_r950119438_

**Comment by Flova** [comment]
Thanks for opening the issue. 

As the virtual season approaches, we would like to use the official `soccer_ipm` repo. Sadly, we depend on this feature. So we would still need to maintain a fork or filter out detections in an additional node earlier in the pipeline. I am not in favor of both of these things. I would be fine with setting the default out of image threshold value to the exact bottom of the image by default, same goes for additional tests. Referring to the original suggestions, I already put it into the `utils.py` file. 

Overall, I would prefer it if we merge it with #1 right away.

**Comment by Flova** [comment]
I added some tests to #1

**Comment by ijnek** [comment]
As this issue isn't specific to your team, (after thinking about it), I am ok with accepting the changes in the PR. Just have to make sure this is well documented. The solution itself, I believe has room for improvement using other techniques, so if another team suggests an alternative that is generally better, it must be considered.
If the package is already released when the alternative is brought up, we would have to go through a tik-tok deprecation cycle.

**Comment by ijnek** [comment]
Closing, as covered in #3
